package com.ryuge.desafio.exceptions;

public class ContatoNaoEncontradoException extends RuntimeException {
    public ContatoNaoEncontradoException(Long id) {
        super("Contato n√£o encontrado com o ID: " + id);
    }
}
